Rigid Body Dynamics Library: include/rbdl/CasadiMath/MX_Xd_utils.h File Reference
MX_Xd_utils.h File Reference
Namespaces
RBDLCasadiMath
Functions
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator* (const MX_Xd_static< nrows, ncols > &me, const MX_Xd_scalar &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator* (const MX_Xd_static< nrows, ncols > &me, const double &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator* (const MX_Xd_scalar &other, const MX_Xd_static< nrows, ncols > &me)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator* (const double &other, const MX_Xd_static< nrows, ncols > &me)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator+ (const MX_Xd_static< nrows, ncols > &me, const MX_Xd_dynamic &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator+ (const MX_Xd_static< nrows, ncols > &me, const MX_Xd_SubMatrix &other)
MX_Xd_scalar operator+ (MX_Xd_scalar me, const MX_Xd_SubMatrix &other)
MX_Xd_scalar operator+ (MX_Xd_scalar me, const double &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator+ (const MX_Xd_SubMatrix &me, const MX_Xd_static< nrows, ncols > &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_static< nrows, ncols > &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_static< nrows, ncols > &me, const MX_Xd_dynamic &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_static< nrows, ncols > &me, const MX_Xd_SubMatrix &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_SubMatrix &me, const MX_Xd_static< nrows, ncols > &other)
MX_Xd_dynamic operator* (const MX_Xd_SubMatrix &me, const MX_Xd_scalar &other)
MX_Xd_dynamic operator* (const MX_Xd_SubMatrix &me, const MX_Xd_SubMatrix &other)
MX_Xd_SubMatrix operator/ (const MX_Xd_SubMatrix &me, const MX_Xd_SubMatrix &scalar)
MX_Xd_SubMatrix operator/ (const MX_Xd_SubMatrix &me, const double &scalar)
MX_Xd_dynamic operator* (const MX_Xd_scalar &m1, const MX_Xd_dynamic m2)
MX_Xd_dynamic operator* (const double &m1, const MX_Xd_dynamic m2)
MX_Xd_dynamic operator* (const double &m1, const MX_Xd_SubMatrix m2)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic operator* (const MX_Xd_static< nrows, ncols > &m1, const MX_Xd_dynamic m2)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic operator* (const MX_Xd_dynamic m1, const MX_Xd_static< nrows, ncols > &m2)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic operator* (const MX_Xd_SubMatrix &m1, const MX_Xd_static< nrows, ncols > &m2)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic operator* (const MX_Xd_static< nrows, ncols > &m1, const MX_Xd_SubMatrix &m2)
MX_Xd_dynamic operator/ (double scalar, MX_Xd_SubMatrix mat)
MX_Xd_dynamic operator/ (double scalar, MX_Xd_dynamic mat)
MX_Xd_scalar operator/ (double scalar, const MX_Xd_scalar &mat)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic operator/ (double scalar, MX_Xd_static< nrows, ncols > mat)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator+ (const MX_Xd_dynamic &me, const MX_Xd_static< nrows, ncols > &other)
MX_Xd_dynamic operator- (const MX_Xd_dynamic &me)
MX_Xd_dynamic operator- (const MX_Xd_SubMatrix &me)
MX_Xd_dynamic operator- (MX_Xd_SubMatrix me, const MX_Xd_scalar &scalar)
MX_Xd_scalar operator- (MX_Xd_scalar me, const MX_Xd_SubMatrix &other)
MX_Xd_scalar operator+ (const MX_Xd_dynamic &me, const MX_Xd_scalar &other)
MX_Xd_scalar operator+ (const MX_Xd_scalar &me, const MX_Xd_dynamic &other)
MX_Xd_dynamic operator+ (const MX_Xd_SubMatrix &me, const MX_Xd_dynamic &other)
MX_Xd_dynamic operator+ (const MX_Xd_dynamic &me, const MX_Xd_SubMatrix &other)
MX_Xd_dynamic operator+ (MX_Xd_SubMatrix me, const MX_Xd_SubMatrix &other)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_dynamic &me, const MX_Xd_static< nrows, ncols > &other)
MX_Xd_scalar operator- (const MX_Xd_dynamic &me, const MX_Xd_scalar &other)
MX_Xd_scalar operator- (const MX_Xd_scalar &me, const MX_Xd_dynamic &other)
MX_Xd_dynamic operator- (const MX_Xd_SubMatrix &me, const MX_Xd_dynamic &other)
MX_Xd_dynamic operator- (const MX_Xd_dynamic &me, const MX_Xd_SubMatrix &other)
MX_Xd_dynamic operator- (const MX_Xd_SubMatrix &me, const MX_Xd_SubMatrix &other)
MX_Xd_scalar operator* (double other, const MX_Xd_scalar &me)
MX_Xd_scalar operator+ (double other, const MX_Xd_scalar &me)
MX_Xd_scalar operator- (const MX_Xd_scalar &other)
MX_Xd_scalar operator- (double other, const MX_Xd_scalar &me)
RBDLCasadiMath::MX_Xd_scalar exp (const RBDLCasadiMath::MX_Xd_scalar &x)
MX_Xd_scalar sqrt (const MX_Xd_scalar &x)
MX_Xd_scalar sin (const MX_Xd_scalar &x)
MX_Xd_scalar asin (const MX_Xd_scalar &x)
MX_Xd_scalar cos (const MX_Xd_scalar &x)
MX_Xd_scalar acos (const MX_Xd_scalar &x)
MX_Xd_scalar tan (const MX_Xd_scalar &x)
MX_Xd_scalar atan2 (const MX_Xd_scalar &x, const MX_Xd_scalar &y)
MX_Xd_scalar tanh (const MX_Xd_scalar &x)
bool isnan (const casadi::MX &x)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic fabs (const MX_Xd_dynamic &m)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_scalar fabs (const MX_Xd_static< nrows, ncols > &m)
MX_Xd_scalar fabs (const MX_Xd_scalar &m)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > pow (const MX_Xd_static< nrows, ncols > &m, int exponent)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > pow (const MX_Xd_static< nrows, ncols > &m, unsigned int exponent)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > pow (const MX_Xd_static< nrows, ncols > &m, double exponent)
MX_Xd_scalar pow (const MX_Xd_scalar &m, int exponent)
MX_Xd_scalar pow (const MX_Xd_scalar &m, unsigned int exponent)
MX_Xd_scalar pow (const MX_Xd_scalar &m, double exponent)
Function Documentation
acos()
MX_Xd_scalar std::acos (const MX_Xd_scalar & x) inline
Definition at line 348 of file MX_Xd_utils.h.
References std::acos().
asin()
MX_Xd_scalar std::asin (const MX_Xd_scalar & x) inline
Definition at line 342 of file MX_Xd_utils.h.
References std::asin().
atan2()
MX_Xd_scalar std::atan2 (const MX_Xd_scalar & x, const MX_Xd_scalar & y) inline
Definition at line 354 of file MX_Xd_utils.h.
References std::atan2().
cos()
MX_Xd_scalar std::cos (const MX_Xd_scalar & x) inline
Definition at line 345 of file MX_Xd_utils.h.
References std::cos().
exp()
RBDLCasadiMath::MX_Xd_scalar exp (const RBDLCasadiMath::MX_Xd_scalar & x) inline
Definition at line 329 of file MX_Xd_utils.h.
fabs() [1/3]
MX_Xd_dynamic std::fabs (const MX_Xd_dynamic & m) inline
Definition at line 365 of file MX_Xd_utils.h.
References std::fabs().
fabs() [2/3]
MX_Xd_scalar std::fabs (const MX_Xd_scalar & m) inline
Definition at line 372 of file MX_Xd_utils.h.
References std::fabs().
fabs() [3/3]
MX_Xd_scalar std::fabs (const MX_Xd_static< nrows, ncols > & m) inline
Definition at line 369 of file MX_Xd_utils.h.
References std::fabs().
isnan()
bool std::isnan (const casadi::MX & x) inline
Definition at line 360 of file MX_Xd_utils.h.
References std::isnan().
pow() [1/6]
MX_Xd_scalar std::pow (const MX_Xd_scalar & m, double exponent) inline
Definition at line 394 of file MX_Xd_utils.h.
References std::pow().
pow() [2/6]
MX_Xd_scalar std::pow (const MX_Xd_scalar & m, int exponent) inline
Definition at line 388 of file MX_Xd_utils.h.
References std::pow().
pow() [3/6]
MX_Xd_scalar std::pow (const MX_Xd_scalar & m, unsigned int exponent) inline
Definition at line 391 of file MX_Xd_utils.h.
References std::pow().
pow() [4/6]
MX_Xd_static<nrows, ncols> std::pow (const MX_Xd_static< nrows, ncols > & m, double exponent) inline
Definition at line 385 of file MX_Xd_utils.h.
References std::pow().
pow() [5/6]
MX_Xd_static<nrows, ncols> std::pow (const MX_Xd_static< nrows, ncols > & m, int exponent) inline
Definition at line 377 of file MX_Xd_utils.h.
References std::pow().
pow() [6/6]
MX_Xd_static<nrows, ncols> std::pow (const MX_Xd_static< nrows, ncols > & m, unsigned int exponent) inline
Definition at line 381 of file MX_Xd_utils.h.
References std::pow().
sin()
MX_Xd_scalar std::sin (const MX_Xd_scalar & x) inline
Definition at line 339 of file MX_Xd_utils.h.
References std::sin().
sqrt()
MX_Xd_scalar std::sqrt (const MX_Xd_scalar & x) inline
Definition at line 336 of file MX_Xd_utils.h.
References std::sqrt().
tan()
MX_Xd_scalar std::tan (const MX_Xd_scalar & x) inline
Definition at line 351 of file MX_Xd_utils.h.
References std::tan().
tanh()
MX_Xd_scalar std::tanh (const MX_Xd_scalar & x) inline
Definition at line 357 of file MX_Xd_utils.h.
References std::tanh().